name: ss_crmeducativo_2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_clean_architecture: ^5.0.0
  flutter_svg: ^0.22.0
  sqflite: ^2.0.0+3
  http: ^0.13.1
  json_serializable: ^4.1.1
  moor_flutter: ^4.0.0
  flutter_launcher_icons: ^0.9.0
  #flutter_launcher_name: ^0.0.1

  ionicons: ^0.1.2
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.8
  lottie: ^1.0.1
  photo_view: ^0.11.1

  flutter_inappwebview: ^5.3.2
  data_connection_checker: ^0.3.4
  #esys_flutter_share: ^1.0.2
  #smart_text_view: ^0.1.0
  image_picker: ^0.7.4
  image_cropper: ^1.3.1
  flutter_image_compress: ^1.0.0
  email_validator: ^2.0.1
  intl: ^0.17.0

  package_info: ^2.0.0
  html: ^0.15.0
  scroll_to_index: ^2.0.0
  plugin_platform_interface: ^2.0.0

  #fancy_shimmer_image: ^1.2.0
  shimmer: ^2.0.0
  #fancy_shimmer_image: ^1.2.0
  moor_db_viewer: ^4.0.0
  #sized_context: ^0.2.1+1
  #table_sticky_headers: ^2.0.0 // se modifo esta version para funcione con un solo scroling quitando la etiqueta Expande
  #fdottedline: ^1.0.1
  sliding_sheet: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  moor_generator: ^4.2.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/icons/pack1/
    - assets/icons/pack2/
    - assets/icons/tipo_actividad/
    - assets/images/
    - assets/educar/
    - assets/docentementor/
    - assets/tab/
    - assets/images/archivos/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/gotham.ttf
          #    - family: Roboto
          #fonts:
          #- asset: assets/fonts/Roboto-Regular.ttf
          #- asset: assets/fonts/Roboto-Medium.ttf
          #weight: 400
          #- asset:  assets/fonts/Roboto-Bold.ttf
          #weight: 700
    - family: TT-Norms-Medium
      fonts:
        - asset: assets/fonts/TT-Norms-Pro-Medium.ttf
    - family: TT-Norms-Ligth
      fonts:
        - asset: assets/fonts/TT-Norms-Pro-Light.ttf
    - family: TT-Norms
      fonts:
        - asset: assets/fonts/TT-Norms-Pro-Regular.ttf
        - asset: assets/fonts/TT-Norms-Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/TT-Norms-Pro-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
