enum TipoRecursosUi{
  TIPO_VIDEO, TIPO_VINCULO, TIPO_DOCUMENTO, TIPO_IMAGEN, TIPO_AUDIO, TIPO_HOJA_CALCULO, TIPO_DIAPOSITIVA, TIPO_PDF, TIPO_VINCULO_YOUTUBE, TIPO_VINCULO_DRIVE, TIPO_RECURSO, TIPO_ENCUESTA/*Nuevo tipo link para realizar una encuesta*/
}