class DomainTipos{
  static const int TIPO_RECURSO_VIDEO = 379, TIPO_RECURSO_VINCULO = 380, TIPO_RECURSO_DOCUMENTO = 397, TIPO_RECURSO_HOJA_CALUCLO = 400, TIPO_RECURSO_IMAGEN = 398, TIPO_RECURSO_AUDIO = 399, TIPO_RECURSO_DIAPOSITIVA = 401, TIPO_RECURSO_PDF = 402, TIPO_RECURSO_MATERIALES = 403, TIPO_RECURSO_YOUTUBE = 581;

  static const int TIPO_ACTIVIDAD_CONECTA = 585, TIPO_ACTIVIDAD_TEORIA = 586, TIPO_ACTIVIDAD_APRENDIZAJE = 587, TIPO_ACTIVIDAD_PRACTICA = 588;

}